PR#1
gorobot-nz/go-reserve-task pull request #1
Opened 2021-12-24 09:25 UTC by gorobot-nz

2021-12-24 09:26 UTC, rast1025 commented on docker-compose.yml
> +      - 8000:8000
do not forget to add explicit interface. ex `127.0.0.1:8000:8000`

2021-12-24 09:27 UTC, rast1025 commented on docker-compose.yml
> +      - 5432:5432
same here as well

2021-12-24 09:31 UTC, rast1025 commented on internal/domain/book.go
> +	GetBookById(ctx context.Context, id int64) (Book, error)
Better to return `*Book, error`, so in repository method in case of error you can return `nil, err`

2021-12-24 09:32 UTC, rast1025 commented on internal/domain/book.go
> +	GetBookById(ctx context.Context, id int64) (Book, error)
same here

2021-12-24 09:44 UTC, gorobot-nz commented on internal/domain/book.go
> +	GetBookById(ctx context.Context, id int64) (Book, error)
Fix

2021-12-24 09:44 UTC, gorobot-nz commented on internal/domain/book.go
> +	GetBookById(ctx context.Context, id int64) (Book, error)
Fix

2021-12-24 09:48 UTC, rast1025 requested changes

2021-12-24 09:48 UTC, rast1025 commented on internal/server/server.go
> +func NewApp() *App {
Better handle empty envs in separate func. Something like 
```go
func checkEnvVars() {
	requiredEnvs := []string{"POSTGRES_HOST", "POSTGRES_USER"}
	var msg []string
	for _, el := range requiredEnvs {
		val, exists := os.LookupEnv(el)
		if !exists || len(val) == 0 {
			msg = append(msg, el)
		}
	}
	if len(msg) > 0 {
		log.Fatal(strings.Join(msg, ", "), " env(s) not set")
	}
}
```

2021-12-24 09:48 UTC, rast1025 commented on .env
> +POSTGRES_USER=postgres
Do not export .env file with passwords, make .local_env instead

2021-12-24 09:48 UTC, rast1025 commented on Dockerfile
> +FROM golang:latest
Read about multi stage build in golang. Build binary using golang image, use alpine image to run binary

2021-12-24 09:48 UTC, rast1025 commented on internal/book/handler/http/handler.go
> +	context.JSON(http.StatusOK, map[string]interface{}{
you also can use gin.H as alias for map[string]interface

2021-12-24 09:48 UTC, rast1025 commented on internal/domain/book.go
> +	Year    string         `json:"year" binding:"required" db:"book_year"`
do not forget to add validation to year field as date layout

2021-12-26 00:12 UTC, gorobot-nz commented on docker-compose.yml
> +      - 5432:5432
Fix

2021-12-26 00:12 UTC, gorobot-nz commented on docker-compose.yml
> +      - 8000:8000
Fix

2021-12-26 00:12 UTC, gorobot-nz commented on internal/server/server.go
> +func NewApp() *App {
Change

2021-12-27 07:40 UTC, rast1025 approved these changes

2021-12-27 09:59 UTC, rast1025 commented
```
FROM golang:latest AS builder

WORKDIR /app

RUN go version
ENV GOPATH=/

COPY ./ ./

RUN chmod +x wait-for-postgres.sh

RUN go mod download
RUN go mod tidy
RUN go build -o go-tech-task ./cmd/api/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=0 /app/wait-for-postgres.sh .
COPY --from=0 /app/go-tech-task .

RUN apk --update add postgresql-client

CMD ["./go-tech-task"]
```

2021-12-27 22:20 UTC, merged